Fixed syntax error on skills.py
Getting the following error on attempted compile test. Test was ran on Windows PC using Git Bash with a virtual environment running python 3.10.
----------------------------------------------------------------------------------------------------------
$ python -m py_compile skills.py
  File "skills.py", line 64
    print(f'\nOften used skills with "{skills_graph.nodes[selected_skill]['label']} ({selected_skill})":')
                                                                           ^^^^^
SyntaxError: f-string: unmatched '['
(venv)
----------------------------------------------------------------------------------------------------------

Found that this error was due to improper nested single and double quotation marks in the print command. Adjusted single vs double quotation marks such that skills.py will now compile.